### ISSUE TITLE
White / transparent bar at top of Apple Web App on iOS

### ISSUE THREAD

**Issue by richwebb13** [tkuther/piwigo-bootstrap-darkroom#136]
When using this theme and creating a Web App on iOS, a white / transparent bar is left at the top.

Sometimes it is a transparent bar, other times (using Photoswipe gallery) it is white.

![img_c73a9b3d00ab-1](https://user-images.githubusercontent.com/34236990/33550915-88f25eea-d8e7-11e7-872c-bfe8071eed5a.jpeg)

![img_1033](https://user-images.githubusercontent.com/34236990/33551077-2232dc10-d8e8-11e7-9268-e3d8bf816ba4.PNG)

**Comment by richwebb13** [comment]
Further investigation shows it is a result of the implementation of:

<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

In the end I found the visual appearance looked better with "black" rather than "black-translucent".  This avoids the transparency above the toolbar in the first image and the odd white bar above the black frame in the second (not visible given background above).  Not sure if others, using other colour combinations or themes choices might have a different preference.  Ideally I would like to remove the status bar entirely, but this doesn't seem to be possible.

**Comment by tkuther** [comment]
Last time I tried the web app function was mostly useless anyway, because Piwigo is a multi-page application (so most links would open safari). In other words: this "feature" isn't really supported at all, neither by the theme nor by Piwigo itself.
Opening Photoswipe directly from the Album page could work, but that's pretty much all.
