### ISSUE TITLE
On picture screen, unable to scroll next thumbnail.

### ISSUE THREAD

**Issue by miceno** [tkuther/piwigo-bootstrap-darkroom#171]
In small screens (720x1280), the box for the info (IPTC, EXIF) has a higher z-index than other elements on the screen.

In particular, the `#carousel-container` element and the buttons to move to next thumbnail appear below the `#sidebar`.

A simple patch will be adding a higher z-index to both `slick-arrow`s, like this:

```
#thumbnailCarousel > button.slick-arrow {
  z-index: 150;
}
```

It is not clear to me where to add these CSS, so I am posting the issue here instead of commiting it to a PR.

Thanks in advance!

**Comment by tkuther** [comment]
This sounds rather wrong, because, as you said, the carousel buttons are below the #sidebar. Giving it a higher z-index would just cause this:

Button is rendered above the sidebar, but might have exact same color (so you don't see it):
![bildschirmfoto 2018-08-15 um 14 59 24](https://user-images.githubusercontent.com/63717/44149304-ec72a46c-a09b-11e8-99aa-223015e6a9e1.png)

Highlight reveals it (and it happens to overlay with the text "below" it)
![bildschirmfoto 2018-08-15 um 14 58 58](https://user-images.githubusercontent.com/63717/44149306-ee98f340-a09b-11e8-891f-1694a3bd4f2b.png)

So I don't see any real usability improvement here, but it might cause visual glitches if the button doesn't happen to have the same color.

You can just use the mouse to swipe through the carousel on desktop devices.
