### ISSUE TITLE
Substitute `<map>` and `<area>` by `<a>`

### ISSUE THREAD

**Issue by miceno** [tkuther/piwigo-bootstrap-darkroom#172]
On picture screen, the picture image has a `<map>` element with different `<area>`s. The issue is that coordinates are written as pixel coordinates. Pixel coordinates may not be right, since on small screens, images are scaled in order to fit on the screen.

For instance, on a mobile with a screen of 720x1280, piwigo render images as 792x594, and coordinates on the `<area>` are like this:

```css
<map name="mapmedium">
    <area shape="rect" coords="0,0,198,594" 
        href="picture.php?/5237/category/seleccionines" title="Previous : IMG 0002" alt="IMG 0002">
    <area shape="rect" coords="198,0,591,148" 
        href="index.php?/category/seleccionines" title="Thumbnails" alt="Thumbnails">
    <area shape="rect" coords="595,0,792,594" 
        href="picture.php?/5239/category/seleccionines" title="Next : IMG 0026" alt="IMG 0026">
</map>```

The issue is that due to responsive layout, the size of the image is about 720x540, so the areas are not render properly and thus, the user gets confused when it clicks on the image areas.

I suggest substituting `<map>` and `<area>` by `<a>` so it will be easier to create relative sized anchors that will fit into any screen.

**Comment by tkuther** [comment]
Could you create a pull request that shows what you mean with "replacing `<map>`and `<area>` with `<a>`" exactly, because I don't seem to be able to reproduce any usability issue here.

Resizing the browser window to 1280x720 and choosing medium derivative format (792x594), I get three clickable areas: 
![areas](https://user-images.githubusercontent.com/63717/44148442-b4ef41d8-a098-11e8-9878-6a5b097c60b9.png)
left: prev image
center top: up to category
right: next image

..which is pretty much how it's supposed to be.

So, how would you implement the three prev/up/next areas using `<a>` then? Do you mean a single `<a>` for the whole image, and if yes, where would it link to?

Maybe I'm just not getting it, which is why I ask for a pull request.
