### ISSUE TITLE
Auto Play Videos in Slideshow Mode

### ISSUE THREAD

**Issue by GreggShimokura** [tkuther/piwigo-bootstrap-darkroom#179]
I was wondering if was possible as part of slideshow mode to autoplay any videos that are present instead of having to click and then close each video as they appear.

Is this an easy feature to add or enable?

**Comment by tkuther** [comment]
This is generally not possible on mobile devices, and discouraged on desktop, too.

**Comment by WisdomCode** [comment]
Because that bugged me as well, I wrote a pretty cheap way for enabling autoplay in the slideshow in my fork
https://github.com/WisdomCode/piwigo-bootstrap-darkroom
@tkuther you may merge it if you want to, if not others finding this issue might be interested. It also makes the video autoloop, as I found it particulary useful for gifs (as a form of medium, like on gfycat, not the fileformat, which has often become insufficient for exactly this task)
