### ISSUE TITLE
add quick search box

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#28]
Is it possible to move the quick search box from inside the menu entry to the left of the menu bar, say for example, to the left of the albums dropdown? This way its always visible and easier to find for some visitors

Thanks!

**Comment by tkuther** [comment]
I might add an option for this in the future. Currently it would require "moving" the search box using jquery. Requires some basic jQuery knowledge and a personal plugin as shown here: https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Add-custom-CSS-and-Javascript

**Comment by konservat0r** [comment]
@tkuther You can give instructions for the search moving? :) for the average user))

**Comment by tkuther** [comment]
@konservat0r OK, here you go.

Go to Administration -> Plugins -> Local Files Editor -> Personal Plugin. 
Paste this somewhere between the `<?php`....`?>` tags

```
add_event_handler('init', 'add_qsearch_to_navbar');
function add_qsearch_to_navbar() {
  global $template;

  $script_content = <<<EOT
$(document).ready(function() {
  $('#qsearchInput').closest('.navbar-form').clone().appendTo('.navbar-main .navbar-header').css({"float":"left"});
})

EOT;
  $template->block_footer_script(array('require' => 'jquery'), $script_content);
}
```

**Comment by pablopeu** [comment]
Thanks for the 1.5.5 update Thomas!
Tried this plugin, its a step forward but looks kludgy, Im sure when you integrate it properly will flow nicer.

For example:
On mobile, quick search could be located on top of the pulldown menu, not inside the menu item.

On desktop it attaches itself next to the page logo, a more nice place would be to the left of the first menu, or to the far right of the menu (with or without additional menu pages)

**Comment by tkuther** [comment]
It does indeed look strange on your site, mainly due to the wide logo image. Prepending it to the left side menu looks better in that case. But the way bootstrap works will cause even more trouble on devices where space is limited, but bootstrap does not collapse the menu yet. Say an iPad in portrait orientation mode:

![bildschirmfoto 2017-02-25 um 21 36 46](https://cloud.githubusercontent.com/assets/63717/23334617/a39b8334-fba2-11e6-91bd-bece0b89a064.png)
Fail.
Or, if your gallery has a really long title: fail.
Or, if you add some menu entry using additional pages: fail.
Or if you have a wide logo image: fail.

Those issues exist already and make the menu span two rows and look awful, a search box will make it even worse.

So while I do like the idea, I think it does require more work and a good idea how to make it work best across all devices.

**Comment by tkuther** [comment]
Oh, and I guess the main usability issue here is that nobody would expect the search functionality under that "Menu" menu entry in the main menu. See, that sounds ridiculous, and that's exactly the issue.

**Comment by pablopeu** [comment]
For mobile if what I simulated here in photoshop were possible it would be great:

[img]http://i.imgur.com/prAmYeA.png[/img]

**Comment by pablopeu** [comment]
For Desktop, a loupe icon on the far right of the menu that opens the quick search box (right aligned) its more usable than its actual location methinks and its easier to find. Not sure if its possible...

http://i.imgur.com/RmmE07c.jpg

**Comment by pablopeu** [comment]
wow! thanks! can't wait 👍

**Comment by konservat0r** [comment]
@tkuther great! We aspire to perfect template :)
