### ISSUE TITLE
Migrate to Bootstrap v4

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#86]
Bootstrap has just released a new version v4.0.0-alpha.6 piwigo-bootstrap-darkroom needs to be updated with this new version or is that useless? Thank you

https://v4-alpha.getbootstrap.com/

**Comment by tkuther** [comment]
Err, no. The theme uses last stable boostrap 3.x. v4-alpha is, well, alpha.

**Comment by tkuther** [comment]
Now that Bootstrap 4 beta is out, let's reopen this one.

Work is taking place in the bootstrap4 branch.

Things to note so far:
- all navbars need to be migrated (mostly done)
- all panels and wells need to be ported to cards
- the thumbnail grid needs to be rewritten, mostly
- bootswatch and material v4 branches are currently messed up due to breaking changes in the beta vs alpha6
- jasny-bootstrap's navmenu (for that vertical secondary menu on mobile devices) will be dropped in favor of bootstrap4's native support for vertical navbars

Most likely I will drop bootstrapdefault as parent, too, as _all_ templates need to be changed. So the only things left are the config options in the admin section, tag cloud and such. Let's just merge those.

**Comment by tkuther** [comment]
Migration is done. 2.x will be based on Bootstrap 4.
